import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
import { Providers } from "./providers";
import { i18n, Locale } from "@/src/config/i18n.config";
import { ReactNode } from "react";
import { getDictionaryServerOnly } from "@/src/dictionaries/default-dictionary-server-only";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export async function generateStaticParams() {
  const languages = i18n.locales.map((lang)=>({lang}));
  return languages
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: Promise<{ lang: Locale }>; // still a Promise in async Server Component
}) {
  const { lang } = await params; // unwrap the Promise
  const dict = await getDictionaryServerOnly(lang);


  return (
    <html lang={lang}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers dict={dict}>{children}</Providers>
      </body>
    </html>
  );
}

